android: [NFC] Expose the ReleaseModeModelRunner
Porting of commit:
db5aceb ("[NFC] Expose the ReleaseModeModelRunner")

Fixes the following building error:

error: external/llvm-project/llvm/lib/Analysis/Android.bp:1:1: module "libLLVM14Analysis" variant "linux_glibc_x86_64_sta
tic": module source path "external/llvm-project/llvm/lib/Analysis/ReleaseModeModelRunner.cpp" does not exist