android: fix llvm-tblgen build by bringing back llvm/CodeGen/MachineValueType.h
Essential revert of commit 631bfdb "Switch llvm/CodeGen/MachineValueType.h to the generated one"

Fixes the following building error:

In file included from external/llvm-project/llvm/utils/TableGen/GlobalISel/GIMatchDag.cpp:13:
In file included from external/llvm-project/llvm/utils/TableGen/GlobalISel/../CodeGenInstruction.h:19:
external/llvm-project/llvm/include/llvm/CodeGen/MachineValueType.h:43:10: fatal error: 'llvm/CodeGen/GenVT.inc' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.