android: lib/Analysis: add explicit list of sources
After commit bdceefe95ba ("[llvm] Release-mode ML InlineAdvisor")
some sources are built conditionally based on LLVM_HAVE_TF_AOT

To make it simple the explict list of source is expanded
and Release-mode ML InlineAdvisor is kept disable (i.e. not built)
to avoid the following building error:

external/llvm-project/llvm/lib/Analysis/ReleaseModeModelRunner.cpp:18:10:
fatal error: 'InlinerSizeModel.h' file not found
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.

Signed-off-by: Mauro Rossi <issor.oruam@gmail.com>