android: Target/Mips: fix Intrinsics dependencies
Needed to avoid following building errors:

In file included from external/llvm/lib/Target/Mips/InstPrinter/MipsInstPrinter.cpp:16:
In file included from external/llvm/lib/Target/Mips/InstPrinter/../MipsInstrInfo.h:23:
In file included from external/llvm/lib/Target/Mips/InstPrinter/../MipsRegisterInfo.h:18:
In file included from external/llvm/lib/Transforms/Hello/../../../include/llvm/CodeGen/MachineBasicBlock.h:22:
In file included from external/llvm/lib/Transforms/Hello/../../../include/llvm/CodeGen/MachineInstr.h:24:
In file included from external/llvm/lib/Transforms/Hello/../../../include/llvm/CodeGen/MachineOperand.h:18:
external/llvm/lib/Transforms/Hello/../../../include/llvm/IR/Intrinsics.h:42:10: fatal error: 'llvm/IR/Intrinsics.inc' file not found
#include "llvm/IR/Intrinsics.inc"
         ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

In file included from external/llvm/lib/Target/Mips/TargetInfo/MipsTargetInfo.cpp:11:
In file included from external/llvm/lib/Transforms/Hello/../../../include/llvm/IR/Module.h:26:
In file included from external/llvm/lib/Transforms/Hello/../../../include/llvm/IR/Function.h:33:
external/llvm/lib/Transforms/Hello/../../../include/llvm/IR/Intrinsics.h:42:10: fatal error: 'llvm/IR/Intrinsics.gen' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.