android: [CodeGen] Fix compiler conditional combination
Inspired by commit cac5d0e "[CodeGen] Fix compiler conditional combination"
Required to avoid the following building errors:

external/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:921:13: error: no member named 'VerifyDAGDivergence' in 'llvm::SelectionDAG'
  921 |     CurDAG->VerifyDAGDivergence();
      |     ~~~~~~  ^
external/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:941:13: error: no member named 'VerifyDAGDivergence' in 'llvm::SelectionDAG'
  941 |     CurDAG->VerifyDAGDivergence();
      |     ~~~~~~  ^
external/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:963:13: error: no member named 'VerifyDAGDivergence' in 'llvm::SelectionDAG'
  963 |     CurDAG->VerifyDAGDivergence();
      |     ~~~~~~  ^
external/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:987:15: error: no member named 'VerifyDAGDivergence' in 'llvm::SelectionDAG'
  987 |       CurDAG->VerifyDAGDivergence();
      |       ~~~~~~  ^
external/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:1005:15: error: no member named 'VerifyDAGDivergence' in 'llvm::SelectionDAG'
 1005 |       CurDAG->VerifyDAGDivergence();
      |       ~~~~~~  ^
external/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:1021:15: error: no member named 'VerifyDAGDivergence' in 'llvm::SelectionDAG'
 1021 |       CurDAG->VerifyDAGDivergence();
      |       ~~~~~~  ^
external/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:1041:15: error: no member named 'VerifyDAGDivergence' in 'llvm::SelectionDAG'
 1041 |       CurDAG->VerifyDAGDivergence();
      |       ~~~~~~  ^
external/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:1061:13: error: no member named 'VerifyDAGDivergence' in 'llvm::SelectionDAG'
 1061 |     CurDAG->VerifyDAGDivergence();
      |     ~~~~~~  ^
external/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:1081:13: error: no member named 'VerifyDAGDivergence' in 'llvm::SelectionDAG'
 1081 |     CurDAG->VerifyDAGDivergence();
      |     ~~~~~~  ^
9 errors generated.